run:
  timeout: 5m

linters:
  enable:
    - govet
    - gofmt
    - revive
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign

issues:
  exclude-use-default: false
  max-same-issues: 3
  max-issues-per-linter: 0

